name: Build Check

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Verify HTML/CSS/JS files exist
        run: |
          test -f index.html
          test -f style.css
          test -f script.js
